# Generated by Django 5.1.2 on 2024-10-16 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_remove_task_fim_remove_task_inicio_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
