# Generated by Django 5.1.2 on 2024-10-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_task_fim_task_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
